name: Build Metal

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install dependencies
              run: |
                  brew install ninja

            - name: Configure
              shell: bash
              run: |
                  cmake -S . -B build \
                  -G Ninja \
                  -DBACKEND=AUTO \
                  -DBEZEL_NATIVE=OFF \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

            - name: Build
              shell: bash
              run: |
                  cmake --build build --parallel
